import type { Metadata } from "next";
import "../assets/styles/globals.css";
import Layout from "@/components/Layout";
import CallbackBtn from "@/components/Buttons/CallbackBtn";
import localFont from "next/font/local";

// ========================
// PANTON
// ========================
const panton = localFont({
	src: [
		{
			path: "../assets/fonts/panton/Panton-Trial-Regular.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "../assets/fonts/panton/Panton-Trial-Bold.ttf",
			weight: "700",
			style: "normal",
		},
		{
			path: "../assets/fonts/panton/Panton-Trial-SemiBold.ttf",
			weight: "600",
			style: "normal",
		},
		{
			path: "../assets/fonts/panton/Panton-Trial-Light.ttf",
			weight: "300",
			style: "normal",
		},
		{
			path: "../assets/fonts/panton/PantonNarrow-Trial-Light.ttf",
			weight: "300",
			style: "normal",
		},
		{
			path: "../assets/fonts/panton/PantonNarrow-Trial-Regular.ttf",
			weight: "400",
			style: "normal",
		},
	],
	variable: "--font-panton",
});

// ========================
// PANTON
// ========================
const pnt = localFont({
	src: [
		{
			path: "../assets/fonts/pnt/Panton-Bold.woff2",
			weight: "700",
			style: "normal",
		},
		{
			path: "../assets/fonts/pnt/Panton-SemiBold.woff2",
			weight: "600",
			style: "normal",
		},
		{
			path: "../assets/fonts/pnt/Panton-Regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "../assets/fonts/pnt/Panton-Light.woff2",
			weight: "300",
			style: "normal",
		},
	],
	variable: "--font-pnt",
});

// ========================
// MONTSERRAT
// ========================
const montserrat = localFont({
	src: [
		{
			path: "../assets/fonts/montserrat/Montserrat-Light.ttf",
			weight: "300",
			style: "normal",
		},
		{
			path: "../assets/fonts/montserrat/Montserrat-Regular.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "../assets/fonts/montserrat/Montserrat-Medium.ttf",
			weight: "500",
			style: "normal",
		},
		{
			path: "../assets/fonts/montserrat/Montserrat-Bold.ttf",
			weight: "700",
			style: "normal",
		},
	],
	variable: "--font-montserrat",
});

// ========================
// META
// ========================
export const metadata: Metadata = {
	title: "REC-A | Рекрутинговое агенство",
	description: "Generated by create next app",
};

// ========================
// ROOT LAYOUT
// ========================
export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ru">
			<body className={`${pnt.variable} ${montserrat.variable}`}>
				<Layout>{children}</Layout>
				<CallbackBtn />
			</body>
		</html>
	);
}
