import type { Metadata } from "next";
import "../assets/styles/globals.css";
import Layout from "@/components/Layout"

import localFont from 'next/font/local';
import CallbackBtn from '@/components/Buttons/CallbackBtn';

const panton = localFont({
	src: [
		{
			path: '../assets/fonts/panton/Panton-Trial-Regular.ttf',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../assets/fonts/panton/Panton-Trial-Bold.ttf',
			weight: '700',
			style: 'bold',
		},
		{
			path: '../assets/fonts/panton/Panton-Trial-SemiBold.ttf',
			weight: '600',
			style: 'normal',
		},
		{
			path: '../assets/fonts/panton/Panton-Trial-Light.ttf',
			weight: '300',
			style: 'normal',
		}
	]
});


export const metadata: Metadata = {
	title: "REC-A | Рекрутинговое агенство",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body className={panton.className}>
				<Layout>
					{children}
				</Layout>
				<CallbackBtn />
			</body>
		</html>
	);
}
